### ISSUE TITLE
## merge weights

### ISSUE THREAD

**Issue by douling843** [lizzy8587/CastDet#3]
python tools/merge_weights.py --clip_path <clip_path> --base_path <base_model_path> --save_path <save_init_model_path> --base_model <soft-teacher (default) | faster-rcnn>

Hello author, this is a great job. Can you provide a complete example?

**Comment by LKXHZD** [comment]
Hello author.I would also like an example.For example,where can I find clip_path and base_model_path.Please forgive my ignorance,as I am a novice just starting out.

**Comment by JaggerGu** [comment]
i am encountering the same problem :)

**Comment by LKXHZD** [comment]
I have solved this problem,but the detection rate is very low.This is a code example:
python tools/merge_weights.py --clip_path RemoteCLIP-RN50.pt --base_path iter_80000.pth --save_path checkpoint --base_model soft-teacher

**Comment by JaggerGu** [comment]
> I have solved this problem,but the detection rate is very low.This is a code example: python tools/merge_weights.py --clip_path RemoteCLIP-RN50.pt --base_path iter_80000.pth --save_path checkpoint --base_model soft-teacher

I met some problem when I run it, can you help me to solve it? thanks and best regards
`Traceback (most recent call last):
  File "tools/merge_weights.py", line 43, in <module>
    main()
  File "tools/merge_weights.py", line 40, in main
    merge_weights(args.clip_path, args.base_path, args.save_path, args.base_model)
  File "tools/merge_weights.py", line 15, in merge_weights
    clip = torch.load(clip_path).state_dict()
AttributeError: 'dict' object has no attribute 'state_dict'`

**Comment by JaggerGu** [comment]
> > I have solved this problem,but the detection rate is very low.This is a code example: python tools/merge_weights.py --clip_path RemoteCLIP-RN50.pt --base_path iter_80000.pth --save_path checkpoint --base_model soft-teacher
> 
> I met some problem when I run it, can you help me to solve it? thanks and best regards `Traceback (most recent call last): File "tools/merge_weights.py", line 43, in <module> main() File "tools/merge_weights.py", line 40, in main merge_weights(args.clip_path, args.base_path, args.save_path, args.base_model) File "tools/merge_weights.py", line 15, in merge_weights clip = torch.load(clip_path).state_dict() AttributeError: 'dict' object has no attribute 'state_dict'`

Solved. I deleted the state_dict()

**Comment by douling843** [comment]
> > > I have solved this problem,but the detection rate is very low.This is a code example: python tools/merge_weights.py --clip_path RemoteCLIP-RN50.pt --base_path iter_80000.pth --save_path checkpoint --base_model soft-teacher
> > 
> > 
> > I met some problem when I run it, can you help me to solve it? thanks and best regards `Traceback (most recent call last): File "tools/merge_weights.py", line 43, in <module> main() File "tools/merge_weights.py", line 40, in main merge_weights(args.clip_path, args.base_path, args.save_path, args.base_model) File "tools/merge_weights.py", line 15, in merge_weights clip = torch.load(clip_path).state_dict() AttributeError: 'dict' object has no attribute 'state_dict'`
> 
> Solved. I deleted the state_dict()

When I run python tools/train.py configs/visdrone_step2_castdet_12b_10k.py, I got the following error, please, how can I solve it?

FileNotFoundError: checkpoints/exp42_iter_76000_remote_clip.pth can not be found.
Successfully save queue in work_dirs/visdrone_step2_castdet_12b_10k/0_save_queue_samples.npz

**Comment by LKXHZD** [comment]
There is a path in the last line of the file"visdrone_step2_castdet_12b_10k.py",modify it to the path of the *.pth generated in your previous run.

**Comment by lizzy8587** [comment]
> I have solved this problem,but the detection rate is very low.This is a code example: python tools/merge_weights.py --clip_path RemoteCLIP-RN50.pt --base_path iter_80000.pth --save_path checkpoint --base_model soft-teacher

Thank you, that's correct. I'll update the code later. If you need more help with the detection rate, I could offer some help. Are there any hyperparameters changed (e.g. training schedule, optimizer, threshold, batch size, etc.)?

**Comment by LKXHZD** [comment]
Firstly I change the batch size,then an error occurred.To this end,I change the learning rate policy(e.g. connect the intervals of method LinearLR and method MultiStepL) during the pre training phase.Although this solves the error,the detection rate is only about 15%.May I ask why this is happening and how to solve it?

**Comment by lizzy8587** [comment]
> Firstly I change the batch size,then an error occurred.To this end,I change the learning rate policy(e.g. connect the intervals of method LinearLR and method MultiStepL) during the pre training phase.Although this solves the error,the detection rate is only about 15%.May I ask why this is happening and how to solve it?

Have you considered trying the original batch size? Someone told me earlier that the batch size can affect the results.

**Comment by LKXHZD** [comment]
OK，I will try the original batch size.Thank you.
